name: Deploy to VM

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v4
  
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/satryaputra:latest
  
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.VM_SSH_KEY }}

      - name: Deploy
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} <<'EOF'
            docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
            docker pull ghcr.io/${{ github.repository_owner }}/satryaputra:latest
            docker stop satryaputra || true
            docker rm satryaputra || true
            docker run -d --name satryaputra \
              --cpus 0.10 --memory 64m \
              -p 3000:80 \
              -e DB_CONNECTION_STRING="${{ secrets.DB_CONNECTION_STRING }}" \
              ghcr.io/${{ github.repository_owner }}/satryaputra:latest
          EOF